### ISSUE TITLE
AttributeError bug

### ISSUE THREAD

**Issue by yydxlv** [operalib/operalib#7]
when i am run the demo 
"Joint quantile regression with operator-valued kernels"
An error occured  as belows,  can you fix it , thank you !

AttributeError                            Traceback (most recent call last)
<ipython-input-8-a74c9c71f5b9> in <module>()
     48     plt.show()
     49 if __name__ == '__main__':
---> 50     main()

<ipython-input-8-a74c9c71f5b9> in main()
     30         print(name)
     31         start = time.time()
---> 32         reg.fit(x_train, y_train)
     33         print(name + ' leaning time: ', time.time() - start)
     34         print(name + ' score ', reg.score(x_test, y_test))

D:\Software\Anaconda\lib\site-packages\operalib-0.2b25-py3.6.egg\operalib\quantile.py in fit(self, X, y)
    218             self._qp_nc(gram, y, probs)
    219         else:
--> 220             self._qp(gram, y, probs)
    221         return self
    222 

D:\Software\Anaconda\lib\site-packages\operalib-0.2b25-py3.6.egg\operalib\quantile.py in _qp(self, gram, targets, probs)
    299         self.model_ = {'coefs': coefs, 'intercept': 0}
    300         intercept = [percentile(targets - pred, 100. * prob) for
--> 301                      (pred, prob) in zip(self.predict(self.linop_.X), probs)]
    302         intercept = asarray(intercept).squeeze()
    303         self.model_ = {'coefs': coefs, 'intercept': intercept}

D:\Software\Anaconda\lib\site-packages\operalib-0.2b25-py3.6.egg\operalib\quantile.py in predict(self, X)
    190         check_is_fitted(self, ['model_', 'linop_'], all_or_any=all)
    191         X = check_array(X)
--> 192         return self._decision_function(X)
    193 
    194     def fit(self, X, y):

D:\Software\Anaconda\lib\site-packages\operalib-0.2b25-py3.6.egg\operalib\quantile.py in _decision_function(self, X)
    171         pred = reshape(self.linop_(X) * self.model_['coefs'],
    172                        (n_samples, n_quantiles))
--> 173         pred += self.model_['intercept'].squeeze()
    174 
    175         return pred.T if self.linop_.p > 1 else pred.T.ravel()

AttributeError: 'int' object has no attribute 'squeeze'

**Comment by RomainBrault** [comment]
Thanks for the ticket, I'm looking at it.

**Comment by yydxlv** [comment]
I have fixed it by add a np.asarray() before the "intercept"
